### ISSUE TITLE
Use groups of parameters in `wohngeld.yaml`

### ISSUE THREAD

**Issue by hmgaudecker** [iza-institute-of-labor-economics/gettsim#144]
Having discussed this with @mjbloemer in the afternoon, the following might be a good choice:

```yaml
faktor:
    name:
        de: Faktor am Anfang der Wohngeldformel
        en:
    description:
        de: Anlage 2 WoGG zu §19 Abs. 2 WoGG
        en:
    1984-01-01:
        value: 1
        reference:
    2009-01-01:
        value: 1.08
        reference:
    2016-01-01:
        value: 1.15
        reference: §19 (1) aa) zuletzt geändert durch BGBl. Nr.38 vom 08.10.2015, S.1613

koeffizienten:
    name: Parameter a, b, c der Wohngeldformel
    1984-01-01:
        note: Parameter aus Regressionsanalyse der Wohngeldtabellen
        1:
            a: 0.0532
            b: 0.00135
            c: 0.0000632
        2:
            a:
            b:
            c:
        ...
        12:
            a:
            b:
            c:
```

~No big rush with implementing this, let us first make sure that the piecewise linear grouping works.~
