### ISSUE TITLE
Fix arbeitsl_geld_2.yaml / vermögensfreibetrag

### ISSUE THREAD

**Issue by hmgaudecker** [iza-institute-of-labor-economics/gettsim#325]
### Bug description

The `name` does not conform to our standards (`de_1`, ... instead of `de` only, is that even rendered anywhere?). 

The actual parameters are opaque and seem to mix different concepts. Rather make multiple parameters out of this?

```yaml
vermögensfreibetrag:
  name:
    de_1: Vermögensgrundfreibetrag je Lebensjahr, nach Geburtsjahr, erst ab 2008 unterschiedlich
    de_2: Vermögensfreibetrag für Erstausstattung
    de_3: Vermögensgrundfreibetrag je Kind
    en_1: Basic allowance per year of life, sorted by year of birth, starting 2008 different
    en_2: Allowance for furniture
    en_3: Allowance per child
  description:
    de: § 12 (2) Satz 1 Nr. 1 SGB II.
    en:
  unit: Euro
  2005-01-01:
    standard: 200
    vor_1948: 520
    1948_bis_1957: 13000
    1958_bis_1963: 13000
    nach_1963: 13000
    ausstattung: 750
    kind: 4100
    reference: Artikel 1 G. v. 24.12.2003 BGBl. I S. 2954.
```
