### ISSUE TITLE
Implement `mehrbedarf_behinderung_m_hh` for ALG 2

### ISSUE THREAD

**Issue by ChristianZimpelmann** [iza-institute-of-labor-economics/gettsim#341]
### Current and desired situation

`mehrbedarf_behinderung_m_hh` implemented for Grundsicherung im Alter, but not for ALG 2.

### Proposed implementation

Similarly to `mehrbedarf_behinderung_m_hh` for Grundsicherung im Alter. Might even be able to use the same parameters and function?

**Comment by hmgaudecker** [comment]
This looked like a small thing initially and attempts to tackle it were started in #370 and #372. However, it turned out that a much larger change would be required because disabled persons may either receive Arbeitslosengeld 2 or Grundsicherung bei Erwerbsminderung, potentially adding Mehrbedarf on top of each. Empirically, both programs are quantitatively important.

Summarising the discussion from those PRs (contributors @Eric-Sommer @MaxBlesch @ChristianZimpelmann @hmgaudecker):

> The 'mehrbedarf' for disabled persons can only be applied for disabled persons who are the same time part of the labor force. In addition, they need to receive 'Leistungen zur Teilhabe am Arbeitsleben' oder 'Eingliederungshilfen'. 

> If they are not, they are treated in SGB XII (Grundsicherung bei Erwerbsminderung).

> According to Destatis, there are around 1M recipients for 'Grundsicherung bei Erwerbsminderung' and 'Grundsicherung im Alter'. These are about equally split on those below or above the 'Altersgrenze'. 'Leistungen zur Teilhabe am Arbeitsleben' is received by around 250.000 people. By and large, these are disabled persons employed in specific 'Werkstätten'. Those seem to be the ones that can qualify for the 'Mehrbedarf' under Arbeitslosengeld 2

> So this is quantitatively important, both for accounting reasons and to get labour supply elasticities right. We'll definitely need this distinction.


## Code snippets from #370:

### parameters/arbeitsl_geld_2.yaml
```yaml

mehrbedarf_behindert:
  name:
    de: Mehrbedarf bei Behinderung
    en: Additional requirement when disabled
  description:
    de: Dieser Prozentanteil des Regelbedarfs wird Erwerbsfähigen gewährt, die 'Leistungen
      zur Teilhabe am Arbeitsleben' erhalten.
    en: null
  unit: share
  reference: § 21 Abs. 4 SGB II
  2005-01-01:
    scalar: 0.35


mehrbedarf_min_behinderungsgrad:
  name:
    de: Höhe des Grades der Behinderung, ab dem man Mehrbedarf im Arbeitslosengeld 2 bekommt
    en: This is an english name
  description:
    de: Festgelegte Grenze des Grades der Behinderung. Nicht im Gesetz verankert.
    en: English name
  2005-01-01:
    scalar: 30
```

### arbeitsl_geld_2.py

```py
aggregation_arbeitsl_geld_2 = {
    "anz_arbeitsl_geld_2_behindert_hh": {
        "source_col": "_arbeitsl_geld_2_behindert",
        "aggr": "sum",
    },
}

def _arbeitsl_geld_2_behindert(
    behinderungsgrad: int, alter: int, arbeitsl_geld_2_params: dict
) -> bool:
    """Check if individual is eligible for additional allowance if disabled.
    Parameters
    ----------
    behinderungsgrad
        See basic input variable :ref:`behinderungsgrad <behinderungsgrad>`.
    alter
        See basic input variable :ref:`alter <alter>`.
    arbeitsl_geld_2_params
        See params documentation :ref:`arbeitsl_geld_2_params <arbeitsl_geld_2_params>`.
    Returns
    -------
    """
    out = (
        behinderungsgrad > arbeitsl_geld_2_params["mehrbedarf_min_behinderungsgrad"]
    ) & (alter > 14)
    return out


def _arbeitsl_geld_2_behindert_mehrbedarf_m_hh(
    anz_arbeitsl_geld_2_behindert_hh: bool,
    arbeitsl_geld_2_params: dict,
) -> float:

    """Compute additional need for disabled people.
    Additional need for disabled but employable. Percentage of the Regelbedarf that is added on top.

    Parameters
    ----------
    anz_arbeitsl_geld_2_behindert_hh
        See :func:`_arbeitsl_geld_2_behindert`, summed up to hh level.
    arbeitsl_geld_2_params
        See params documentation :ref:`arbeitsl_geld_2_params <arbeitsl_geld_2_params>`.
    Returns
    -------
    float Percentage of Regelbedarf to be added on top because of disabled persons in the household
    """
    out = (
        anz_arbeitsl_geld_2_behindert_hh
        * arbeitsl_geld_2_params["mehrbedarf_behindert"]
    )
    return out
```

Then will add `_arbeitsl_geld_2_behindert_mehrbedarf_m_hh` appropriately to `arbeitsl_geld_2_regelsatz_m_hh`, its implementation did not get very far and there are  no tests, so better start from scratch.
