### ISSUE TITLE
Make Altersentlastungsbetrag depending on `age` not on current date 

### ISSUE THREAD

**Issue by ChristianZimpelmann** [iza-institute-of-labor-economics/gettsim#350]
### Bug description

[§24a EStG](https://www.gesetze-im-internet.de/estg/__24a.html) specifies that Altersentlastungsbetrag depends on the age or more specifically "Das auf die Vollendung des 64. Lebensjahres folgende Kalenderjahr"

But in our code, we use the same parameter for everybody just based on the current year. The respective parameter is defined as:

```
altersentlastungsbetrag_max:
  name:
    de: Höchstbetrag des Altersentlastungsbetrags
    en: Maximum Amount of Tax Credit for older employees.
  description:
    de: 24a EStG S. 5. Tabelle legt die Werte bis 2040 fest.
    en: If someone receives employment income above the age of 40, a share up to this amount is deducted.
  unit: Euro
  time: year
  2005-01-01:
    scalar: 1900
    reference: Artikel 1 G. v. 05.07.2004 BGBl. I S. 1427.
  2006-01-01:
    scalar: 1824
    reference: Artikel 1 G. v. 05.07.2004 BGBl. I S. 1427.
  2007-01-01:
    scalar: 1748
   ... 
```
### Proposed Solution
- Make separate functions and parameters for the time before 2005 and afterwards
- For the time after 2005, specify parameter as below and make sure that each subject gets assigned the correct Altersentlastungsbetrag based on age

```
altersentlastungsbetrag_max:
  name:
    de: Höchstbetrag des Altersentlastungsbetrags
    en: Maximum Amount of Tax Credit for older employees.
  description:
    de: 24a EStG S. 5. Tabelle legt die Werte bis 2040 fest.
    en: If someone receives employment income above the age of 40, a share up to this amount is deducted.
  unit: Euro
  time: year
  2005-01-01:
    2005: 1900
    2006: 1824
    2007: 1748
    ... 
    reference: Artikel 1 G. v. 05.07.2004 BGBl. I S. 1427.
```
