### ISSUE TITLE
BUG: Installing pre-commit environment failes

### ISSUE THREAD

**Issue by ChristianZimpelmann** [iza-institute-of-labor-economics/gettsim#504]
### Bug description

With the new pre-commits introduced in #500, I get the following error: 
```
An unexpected error has occurred: CalledProcessError: command: ('C:\\.conda\\envs\\gettsim\\python.exe', '-mvirtualenv', 'C:\\Users\\Christian Zimpelmann\\.cache\\pre-commit\\repoiph5buln\\py_env-python3.10', '-p', 'python3.10')
return code: 1
stdout:
    RuntimeError: failed to find interpreter for Builtin discover of python_spec='python3.10'

stderr: (none)
```

- I have python 3.11.0 installed in the environment

Deleting the last line of

```yaml
  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
        # language_version: python3.10
``` 
#### Expected Output

Pre-commits can also be installed if newer Python version than 3.11. is used.
