### ISSUE TITLE
ENH: Minimal example for endogenous groupings

### ISSUE THREAD

**Issue by hmgaudecker** [iza-institute-of-labor-economics/gettsim#582]
#### Is your feature request related to a problem?

In #509, we have been discussing various ways to aggregate individuals into relevant units based on relations between individuals.
- For example, a *Bedarfsgemeinschaft* in SGB II / XII is based on the parent-child relation (`bg_id`)
- A successor for `tax_unit` (Steuersubjekt, `st_id` as tentative names)
- Eligibility for child exemptions in the income tax (`n_kinderfreibeträge`)

The main change is that these units are endogenous now, whereas the only way to set them was as input variables so far.  The functions will be part of the DAG, but they do not operate on a single row, but need to perform merge-like operations. 

Another downstream complication may be that when we do aggregation by `bg_id` or `st_id`, we cannot assume the dataset to be ordered.

#### Minimal test case

This is not a correct depiction of the rules, but should capture the gist of what we need. I use `-1` to indicate missing variables, this is just a placeholder right now.

```yaml
---
info:
  note: >-
    Parents with three kids, assume that one is eligible to be in the same 
    Bedarfsgemeinschaft. One is not because it is living outside the household, another
    is not because it is 25 years of age. Both parents should be a single steuersubject,
    each kid is its own.
  source: ''
inputs:
  provided:
    p_id:
      - 0
      - 1
      - 2
      - 3
      - 4
    hh_id:
      - 0
      - 0
      - 1
      - 0
      - 0
    alter:
      - 50
      - 48
      - 18
      - 20
      - 25
    p_id_ehepartner:
      - 1
      - 0
      - -1
      - -1
      - -1
    p_id_elternteil_1:
      - -1
      - -1
      - 0
      - 0
      - 1
    p_id_elternteil_2:
      - -1
      - -1
      - 1
      - 1
      - 0
outputs:
  bg_id:
    - 0
    - 0
    - 1
    - 0
    - 2
  st_id:
    - 0
    - 0
    - 1
    - 2
    - 3
```
