### ISSUE TITLE
BUG: `fg_id` creation sensitive to order of adults

### ISSUE THREAD

**Issue by MImmesberger** [iza-institute-of-labor-economics/gettsim#801]
### Bug description

@JuergenWiemers drew my attention to the fact that our endogenous `fg_id` creation is sensitive to the order of adults in the data.

Consider the example input below. This is a 3-person household (parent + child and other adult in an Einstandsgemeinschaft with the parent). Note that the order of people in the household is a bit peculiar: First the childless adult, then the child, then the parent. Here, we would expect:

```yaml
  fg_id:
    - 0
    - 0
    - 0
  bg_id:
    - 0
    - 0
    - 0
  eg_id:
    - 0
    - 1
    - 0
```

The result, however is:

```yaml
  fg_id:
    - 0
    - 1
    - 0
  bg_id:
    - 0
    - 100
    - 0
  eg_id:
    - 0
    - 1
    - 0
```

This is due to the loop in our `fg_id` algorithm. There, the algorithm loops over `p_id`s in the data. For a given `p_id`, the loop starts with a candidate `fg_id`, assigns this `fg_id` to the current `p_id`, its Einstandspartner, and its children. The candidate `fg_id` then increases by 1 and the loop continues with the next `p_id` that does not have a matched `fg_id` yet.

The problem in the example below is that, the loop does not recognise the child as an `fg_id` member. In the first iteration, it assigns `fg_id` 0 to the first and last adult (Einstandspartner), but at this point, it does not know that the last adult has children in the household.

From what I see, this is also not solved by sorting the (internal) DataFrame properly in more complicated family structures (e.g. 2 adults and 2 children, each child is from a different partner). 

**Example Input**
```yaml
---
info:
  note: ''
  source: ''
inputs:
  provided:
    p_id:
      - 0
      - 1
      - 2
    alter:
      - 39
      - 13
      - 42
    hh_id:
      - 0
      - 0
      - 0
    p_id_einstandspartner:
      - 2
      - -1
      - 0
    p_id_elternteil_1:
      - -1
      - 2
      - -1
    p_id_elternteil_2:
      - -1
      - -1
      - -1
    eigenbedarf_gedeckt:
      - false
      - false
      - false
outputs:
  fg_id:
    - 0
    - 0
    - 0
  bg_id:
    - 0
    - 0
    - 0
  eg_id:
    - 0
    - 1
    - 0
```
