### ISSUE TITLE
ENH: Interface sketch

### ISSUE THREAD

**Issue by hmgaudecker** [iza-institute-of-labor-economics/gettsim#951]
Just want to jot down some ideas for discussion as I don't have enough time today for putting them into [GEP-7](https://github.com/iza-institute-of-labor-economics/gettsim/pull/855). #948 has a prototype for a new interface that is DAG-based, but still messy (some elements have 70+ characters, that was on purpose though). 

What is clear is that the interface-DAG is complex enough to be structured more clearly. Once more, as with the taxes & transfers-DAG, we should turn to a tree-dags for rescue. That hierarchy could looks something like this:

```yaml
- input_data:
  - tree  # ✅ 
  - df_and_mapper:  # ✅ 
    - df  # ✅ 
    - mapper  # ✅ 
  - df_with_nested_columns
  - flat
  - qname
- targets:
  - tree  # ✅ 
  - qname  # ✅ 
  - flat
  - tree_with_map_to_df  # partly implemented, cannot pass this yet instead of tree.
- policy_environment  # ✅ 
- processed_data  # ✅ 
- orig_policy_objects:  # ✅ 
  - column_objects_and_param_functions  # ✅ 
  - param_specs  # ✅ 
- combined_environment:  # ✅ 
  - with_derived_functions_and_input_nodes  # ✅ 
  - with_processed_params_and_scalars  # ✅ 
  - with_partialled_params_and_scalars  # ✅ 
  - tax_transfer_dag  # ✅ 
  - tax_transfer_function  # ✅ 
- names:
  - target_columns  # ✅ 
  - target_params  # ✅ 
  - targets_from_input_data  # ✅ 
  - top_level_namespace  # ✅ 
  - grouping_levels  # ✅ 
  - processed_data_columns  # ✅ 
  - root_nodes
- raw_results:
  - columns  # ✅ 
  - params  # ✅ 
  - input_columns  # ✅ 
  - combined  # ✅ 
- results:
  - tree  # ✅ 
  - df_with_mapper
  - df_with_nested_columns
  - flat
  - qname
- templates:
  - map_tree_paths_to_to_dtypes
- dates:
  - policy_str
  - policy
  - evaluation_str
  - evaluation
- fail_if:  # ✅ 
  - any_paths_are_invalid  # ✅ 
  - data_tree_is_invalid  # ✅ 
  - ...
- warn_if:  # ✅ 
  - ttsim_objects_and_data_columns_overlap  # ✅ 
```

And one more analogy to the TTSIM-DAG: We'll probably want decorators so we will be able to filter the functions when we load them automatically. Collect some attributes that we want:
- `in_global_namespace: bool`
- `leaf_name`: For picking the right function given inputs. E.g., we may come up with `("input_data", "tree")` based on various sources: DataFrame + Mapper, DataFrame with hierarchical columns, data with qualified names, ... Broadly similar problem to picking the right time conversion function in the TT-DAG.

**Comment by MImmesberger** [comment]
Updated!

**Comment by hmgaudecker** [comment]
New hierarchy with the current state of affairs in #948:

```yaml
input_data:
  tree: ✅
  df_and_mapper:
    df: ✅
    mapper: ✅
  df_with_nested_columns: only interface_input is there, cannot use yet
processed_data: ✅
orig_policy_objects:
  root: ✅
  column_objects_and_param_functions: ✅
  param_specs: ✅
targets:
  qname: ✅
  tree: ✅
names:
  grouping_levels: ✅
  processed_data_columns: ✅
  root_nodes: ✅
  target_columns: ✅
  target_params: ✅
  targets_from_input_data: ✅
  top_level_namespace: ✅
policy_environment: ✅
rounding: ✅
specialized_environment:
  with_derived_functions_and_processed_input_nodes: ✅
  with_processed_params_and_scalars: ✅
  with_partialled_params_and_scalars: ✅
  tax_transfer_dag: ✅
  tax_transfer_function: ✅
raw_results:
  columns: ✅
  params: ✅
  from_input_data: ✅
  combined: ✅
results:
  tree: ✅
  df_with_mapper: ✅
  df_with_nested_columns: untested
fail_if:
  active_periods_overlap: ✅
  any_paths_are_invalid: ✅
  data_paths_are_missing_in_paths_to_column_names: ✅
  environment_is_invalid: ✅
  foreign_keys_are_invalid_in_data: ✅
  group_ids_are_outside_top_level_namespace: ✅
  group_variables_are_not_constant_within_groups: ✅
  input_data_tree_is_invalid: ✅
  input_df_with_mapper_has_bool_or_numeric_column_names: ✅
  input_mapper_has_incorrect_format: ✅
  name_of_last_branch_element_is_not_the_functions_leaf_name: ✅
  non_convertible_objects_in_results_tree: ✅
  root_nodes_are_missing: ✅
  targets_are_not_in_policy_environment_or_data: ✅
  targets_tree_is_invalid: ✅
warn_if:
  functions_and_data_columns_overlap: ✅
```

Comments welcome!
